security:


  role_hierarchy:
    ROLE_UTILISATEUR: ROLE_USER
    ROLE_RESPONSABLE: ROLE_UTILISATEUR
    ROLE_ADMINISTRATEUR: ROLE_RESPONSABLE

  providers:
    membre_Crestic:
      entity: { class: App\Entity\MembresCrestic, property: username }

  firewalls:
    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false
    main:
      custom_authenticator:
          - App\Security\CasAuthenticator
      entry_point: App\Security\CasAuthenticator
      # les urls auxquels s'appliquent ce firewall, dans ce cas, ce sont toutes les urls
      pattern: ^/

      # La connexion n'est pas requise sur toutes les pages
      # par exemple la page d'accueil
      # anonymous: true
      logout:
        path: security_logout
        target: default_homepage
      provider: membre_Crestic


  access_control:
    # Les regles de securité
    # Là dans bin/console make:admin:dashboardce cas seul les utilisateurs ayant le rôle ROLE_ADMIN
    # peuvent acceder à toutes les pages commençant par /admin
    - { path: '^/[a-z]{2}/sso/redirect/cas', roles: PUBLIC_ACCESS }
    #- { path: '^/[a-z]{2}/administration', roles: [ ROLE_ADMINISTRATEUR, ROLE_UTILISATEUR ] }
    - { path: '^/[a-z]{2}/espace-utilisateur', roles: [ ROLE_UTILISATEUR ] }
    - { path: '^/[a-z]{2}/', roles: PUBLIC_ACCESS }

