<?php

namespace App\Repository;

use App\Entity\Agenda;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * AgendaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AgendaRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Agenda::class);
    }

    public function findAll()
    {
        return $this->findBy([], ['type' => 'asc', 'datedebut' => 'desc']);
    }

    public function findEventComing()
    {
        return $this->createQueryBuilder('c')
            ->where('c.datefin > :date')
            ->setParameter('date', new \DateTime('now'))
            ->orderBy('c.datedebut', 'DESC')
            ->getQuery()
            ->getResult();
    }

}
