<?php

namespace App\Repository;

use App\Entity\Departements;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * DepartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepartementsRepository extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Departements::class);
    }

    /**
     * @param null $array_options
     */
    public function findAllDepartementsBuilder($array_options = []): ?\Doctrine\ORM\QueryBuilder
    {
        return $this->createQueryBuilder('a', 'a.id')
            ->orderBy('a.nom', 'ASC');
    }


    /**
     * @param null $array_options
     *
     * @return array
     */

    public function findAllDepartements($array_options = [])
    {
        return $this->findAllDepartementsBuilder($array_options)->getQuery()->getResult();
    }


}
