<?php

namespace App\Repository;

use App\Entity\EquipesHasSliders;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * EquipesHasSlidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesHasSlidersRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, EquipesHasSliders::class);
    }

    public function findAllSlidersFromEquipeBuilder($id_equipe)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.equipe = ?1')
            ->innerJoin('a.slider','b')
            //->orderBy('b.nom','asc')
            ->setParameter(1,$id_equipe);
    }

    public function findAllSlidersFromEquipe ($id_equipe)
    {
        $result = $this->findAllSlidersFromEquipeBuilder($id_equipe)->getQuery()->getResult();

        return $result;
    }

    public function getArrayIdFromEquipeSlider ($id_equipe)
    {
        $result = [];
        $array  =  $this->findAllSlidersFromEquipe($id_equipe);

        foreach ($array as $key=>$value)
        {
            $id = $value->getSlider()->getId();
            $result[] = $id;
        }
        return $result;
    }
}
