<?php

namespace App\Repository;


use App\Entity\EquipesHasDepartements;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * EquipesHasDepartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EquipesHasDepartementsRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, EquipesHasDepartements::class);
    }

    public function findAllDepartementsFromEquipeBuilder($id_equipe)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.equipe = ?1')
            ->innerJoin('a.departement','b')
            ->orderBy('b.nom','asc')
            ->setParameter(1,$id_equipe);
    }

    public function findAllDepartementsFromEquipe ($id_equipe)
    {
        $result = $this->findAllDepartementsFromEquipeBuilder($id_equipe)->getQuery()->getResult();

        return $result;
    }

    public function getArrayIdFromEquipeDepartement ($id_equipe)
    {
        $result = [];
        $array  =  $this->findAllDepartementsFromEquipe($id_equipe);

        foreach ($array as $key=>$value)
        {
            $id = $value->getDepartement()->getId();
            $result[] = $id;
        }
        return $result;
    }

    public function findAllEquipesFromDepartementBuilder($id_departement)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.departement = ?1')
            ->innerJoin('a.equipe','b')
            ->orderBy('b.nom','asc')
            ->setParameter(1,$id_departement);
    }

    public function findAllEquipesFromDepartement ($id_departement)
    {
        $result = $this->findAllEquipesFromDepartementBuilder($id_departement)->getQuery()->getResult();

        return $result;
    }


}
