<?php

namespace App\Repository;


use App\Entity\MembresHasDepartements;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * MembresHasDepartementsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresHasDepartementsRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, MembresHasDepartements::class);
    }

    public function findAllDepartementsFromMembreBuilder($id_membre)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.membre = ?1')
            ->innerJoin('a.departement','b')
            ->orderBy('b.nom','asc')
            ->setParameter(1,$id_membre);
    }

    public function findAllDepartementsFromMembre ($id_membre)
    {
        $result = $this->findAllDepartementsFromMembreBuilder($id_membre)->getQuery()->getResult();

        return $result;
    }

    public function getArrayIdFromMembreDepartement ($id_membre)
    {
        $result = [];
        $array  =  $this->findAllDepartementsFromMembre($id_membre);

        foreach ($array as $key=>$value)
        {
            $id = $value->getDepartement()->getId();
            $result[] = $id;
        }
        return $result;
    }

    public function findAllmembresFromDepartementBuilder($id_departement)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.departement = ?1')
            ->innerJoin('a.membre','b')
            ->orderBy('b.nom','asc')
            ->setParameter(1,$id_departement);
    }

    public function findAllMembresFromDepartement ($id_departement)
    {
        $result = $this->findAllmembresFromDepartementBuilder($id_departement)->getQuery()->getResult();

        return $result;
    }


}
