<?php

namespace App\Repository;

use App\Entity\MembresCrestic;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\Persistence\ManagerRegistry;

/**
 * MembresExterieursRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MembresCresticRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, MembresCrestic::class);
    }

    /**
     * @return array
     */

    public function findAll()
    {
        return $this->findBy([], ['nom' => 'ASC', 'prenom' => 'ASC']);
    }

    public function findByLettre($lettre)
    {
        return $this->createQueryBuilder('m')
            ->where('m.nom LIKE :lettre')
            ->orWhere('m.nom LIKE :lettre2')
            ->andWhere('m.ancienMembresCrestic = false')
            ->setParameters(['lettre'=> $lettre.'%', 'lettre2' => strtolower((string) $lettre).'%'])
            ->orderBy('m.nom', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findWithIdHal()
    {
        return $this->createQueryBuilder('m')
            ->where('m.idhal IS NOT NULL')
            ->orderBy('m.nom', 'ASC')
            ->addOrderBy('m.prenom', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findByExLettre($lettre)
    {
        return $this->createQueryBuilder('m')
            ->where('m.nom LIKE :lettre')
            ->orWhere('m.nom LIKE :lettre2')
            ->andWhere('m.ancienMembresCrestic = true')
            ->setParameters(['lettre'=> $lettre.'%', 'lettre2' => strtolower((string) $lettre).'%'])
            ->orderBy('m.nom', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * @param null $array_options
     */
    public function findAllMembresCresticBuilder($array_options = null): ?\Doctrine\ORM\QueryBuilder
    {
        $result = null;
        if (is_array($array_options) && array_key_exists('role', $array_options)) {

            $result = match ($array_options['role']) {
                'ROLE_ADMINISTRATEUR' => $this->createQueryBuilder('a', 'a.id')
                    ->where('a.ancienMembresCrestic = false')
                    ->orderBy('a.nom', 'ASC'),
                'ROLE_RESPONSABLE' => $this->createQueryBuilder('a', 'a.id')
                    ->where('a.id = ?1 and a.ancienMembresCrestic = false')
                    ->orderBy('a.nom', 'ASC')
                    ->setParameter(1, $array_options['user_id']),
                'ROLE_UTILISATEUR' => $this->createQueryBuilder('a', 'a.id')
                    ->where('a.id = ?1 and a.ancienMembresCrestic = false')
                    ->orderBy('a.nom', 'ASC')
                    ->setParameter(1, $array_options['user_id']),
                'ROLE_VISITEUR' => $this->createQueryBuilder('a', 'a.id')
                    ->where('a.ancienMembresCrestic = false')
                    ->orderBy('a.nom', 'ASC'),
                default => $this->createQueryBuilder('a', 'a.id')
                    ->where('a.ancienMembresCrestic = false')
                    ->orderBy('a.nom', 'ASC'),
            };
        } else {
            $result = $this->createQueryBuilder('a', 'a.id')
                ->where('a.ancienMembresCrestic = false')
                ->orderBy('a.nom', 'ASC');
        }
        return $result;
    }

    /**
     * @param null $array_options
     *
     * @return array
     */

    public function findAllMembresCrestic($array_options = null)
    {
        return $this->findAllMembresCresticBuilder($array_options)->getQuery()->getResult();
    }

    /**
     * @param $responsable
     * @return QueryBuilder
     */
    public function findAllMembresCresticResponsableBuilder($responsable)
    {
        return $this->createQueryBuilder('a','a.id')
            ->where('a.id = ?1 and a.ancienMembresCrestic = false')
            ->orderBy('a.nom', 'ASC')
            ->setParameter(1,$responsable->getId());
    }

    /**
     * @param $responsable
     * @return array
     */

    public function findAllMembresCresticResponsable($responsable)
    {
        return $this->findAllMembresCresticResponsableBuilder($responsable)->getQuery()->getResult();
    }

    /**
     * @return QueryBuilder
     */

    public function findAllConseilLaboratoireBuilder()
    {
        return $this->createQueryBuilder('a','a.id')
            ->where('a.ancienMembresCrestic = false and a.membreConseilLabo = true')
            ->orderBy('a.nom', 'ASC');
    }

    /**
     * @return array
     */

    public function findAllConseilLaboratoire()
    {
        return $this->findAllConseilLaboratoireBuilder()->getQuery()->getResult();
    }

    /**
     * @return QueryBuilder
     */

    public function findAllMembresBuilder()
    {
        return $this->createQueryBuilder('a','a.id')
            ->orderBy('a.nom', 'ASC');

    }

    /**
     * @return array
     */

    public function findAllMembres()
    {
        return $this->findAllMembresBuilder()->getQuery()->getResult();
    }


    /**
     * @return array
     */
    public function getArrayOfChoiceSelectMembresCresticAll()
    {
        $result = [];
        $array = $this->findAllMembres();
        foreach ($array as $key => $value)
        {
            $result['membreCrestic_'.$key] = $value;
        }

        return $result;
    }

    /**
     * @param $status
     * @return array
     */

    public function findAllMembresCresticStatus( $status )
    {
        return $this->findBy(['status' => $status, 'ancienMembresCrestic' => false] , ['nom' => 'ASC', 'prenom' => 'ASC']);
    }

    /**
     * @return array
     */

    public function findAllMembresAncienCrestic()
    {
        return $this->findBy(['ancienMembresCrestic' => true] , ['nom' => 'ASC', 'prenom' => 'ASC']);
    }

    /**
     * @param $status
     * @return array
     */

    public function findAllMembresAncienCresticStatus( $status )
    {
        return $this->findBy(['status' => $status, 'ancienMembresCrestic' => true] , ['nom' => 'ASC', 'prenom' => 'ASC']);
    }

    public function getEquipeResponsableBuilder ()
    {
        return  $this->createQueryBuilder('a')->orderBy('a.nom', 'ASC');
    }

    public function getEquipeResponsable ()
    {
        return  $this->getEquipeResponsableBuilder()->getQuery()->getResult();
    }

    public function findAllNomMembreCresticBuilder ($nom)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.ancienMembresCrestic = 0 AND a.nom LIKE :nom')
            ->setParameter('nom',"%".$nom."%");
    }

    public function findAllNomMembreCrestic ($nom)
    {
        return $this->findAllNomMembreCresticBuilder($nom)->getQuery()->getResult();
    }

    public function findMembreCresticBuilder ($data)
    {
        $qb = $this->createQueryBuilder('a','a.id');
        $qb->orderBy('a.nom', 'ASC');
        $qb->where('a.ancienMembresCrestic = 0');
        $nom = $data['nom'];
        if ($nom != '')
        {
            $qb->andWhere('a.nom LIKE :nom');
            $qb->setParameter('nom',"%".$nom."%");
        }

        $prenom = $data['prenom'];
        if ($prenom != '')
        {
            $qb->andWhere('a.prenom LIKE :prenom');
            $qb->setParameter('prenom',"%".$prenom."%");
        }

        $keywords = $data['keywords'];
        if ($keywords != '')
        {
            $qb->andWhere('a.url LIKE :keywords OR a.cv LIKE :keywords OR a.themes LIKE :keywords OR a.pointsForts LIKE :keywords OR a.responsabilitesScientifiques LIKE :keywords OR a.responsabilitesAdministratives LIKE :keywords OR a.valorisation LIKE :keywords  OR a.enseignements LIKE :keywords OR a.responsabiliteFonction LIKE :keywords');
            $qb->setParameter('keywords',"%".$keywords."%");
        }

        return $qb;
    }


    public function findMembreCrestic ($data)
    {
        return $this->findMembreCresticBuilder($data)->getQuery()->getResult();
    }

    public function findMembreAncienBuilder ($data)
    {
        $qb = $this->createQueryBuilder('a','a.id');
        $qb->orderBy('a.nom', 'ASC');
        $qb->where('a.ancienMembresCrestic = 1');
        $nom = $data['nom'];
        if ($nom != '')
        {
            $qb->andWhere('a.nom LIKE :nom');
            $qb->setParameter('nom',"%".$nom."%");
        }

        $prenom = $data['prenom'];
        if ($prenom != '')
        {
            $qb->andWhere('a.prenom LIKE :prenom');
            $qb->setParameter('prenom',"%".$prenom."%");
        }

        $keywords = $data['keywords'];
        if ($keywords != '')
        {
            $qb->andWhere('a.url LIKE :keywords OR a.cv LIKE :keywords OR a.themes LIKE :keywords OR a.pointsForts LIKE :keywords OR a.responsabilitesScientifiques LIKE :keywords OR a.responsabilitesAdministratives LIKE :keywords OR a.valorisation LIKE :keywords  OR a.enseignements LIKE :keywords OR a.responsabiliteFonction LIKE :keywords');
            $qb->setParameter('keywords',"%".$keywords."%");
        }

        return $qb;
    }


    public function findMembreAncien ($data)
    {
        return $this->findMembreAncienBuilder($data)->getQuery()->getResult();
    }


}
