<?php

namespace App\Repository;

use App\Entity\Partenaires;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PartenairesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PartenairesRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Partenaires::class);
    }

    /**
     * @param null $array_options
     */
    public function findAllPartenairesBuilder($array_options = null): ?\Doctrine\ORM\QueryBuilder
    {
        $result = null;

        switch ($array_options['role'])
        {
            case 'ROLE_ADMINISTRATEUR':
            {
                $result = $this->createQueryBuilder('a','a.id')
                               ->orderBy('a.nom', 'ASC');
                break;
            }

            case 'ROLE_RESPONSABLE':
            {
                break;
            }

            case 'ROLE_MEMBRE':
            {
                break;
            }

            case 'ROLE_VISITEUR':
            {
                break;
            }

            default :
            {
                $result = $this->createQueryBuilder('a','a.id')
                                ->orderBy('a.nom', 'ASC');
                break;
            }
        }

        return $result;
    }

    /**
     * @param null $array_options
     * @return array
     */

    public function findAllPartenaires($array_options = null)
    {
        return $this->findAllPartenairesBuilder($array_options)->getQuery()->getResult();
    }

    public function findInternationaux()
    {
        return $this->createQueryBuilder('p')
            ->where('p.internationale = 1')
            ->orderBy('p.nom', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
