<?php

namespace App\Repository;

use App\Entity\AbsenceJustificatif;
use App\Entity\Pays;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PaysRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PaysRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Pays::class);
    }

    /**
     * @return \Doctrine\ORM\QueryBuilder
     */

    public function findAllPaysBuilder()
    {
        return $this->createQueryBuilder('a','a.id')
            ->orderBy('a.alpha3', 'ASC');

    }

    /**
     * @return array
     */

    public function findAllPays()
    {
        return $this->findAllPaysBuilder()->getQuery()->getResult();
    }
}
