<?php

namespace App\Repository;

use App\Entity\AbsenceJustificatif;
use App\Entity\PlateformesHasSliders;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * PlateformesHasSlidersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlateformesHasSlidersRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, PlateformesHasSliders::class);
    }

    public function findAllSliderFromPlateformeBuilder($id_plateforme)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->innerJoin('a.slider', 'b')
            ->where('a.plateforme = ?1')
            ->setParameter(1,$id_plateforme)
            ->orderBy('b.url','ASC');
    }

    public function findAllSliderFromPlateforme ($id_plateforme)
    {
        return $this->findAllSliderFromPlateformeBuilder($id_plateforme)->getQuery()->getResult();
    }

    public function getArrayIdFromPlateformeSlider ($id_plateforme)
    {
        $result = [];
        $array  =  $this->findAllSliderFromPlateforme($id_plateforme);

        foreach ($array as $key=>$value)
        {
            $id = $value->getSlider()->getId();
            $result[] = $id;
        }
        return $result;
    }
}
