<?php

namespace App\Repository;

use App\Entity\AbsenceJustificatif;
use App\Entity\Projets;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProjetsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Projets::class);
    }

    /**
     * @param null $array_options
     */
    public function findAllProjetsBuilder($array_options = null): ?\Doctrine\ORM\QueryBuilder
    {
        $result = null;

        switch ($array_options['role'])
        {
            case 'ROLE_ADMINISTRATEUR':
            {
                $result =  $this->createQueryBuilder('a','a.id')
                                ->orderBy('a.titre', 'ASC');
                break;
            }

            case 'ROLE_RESPONSABLE':
            {
                $result = $this->createQueryBuilder('a','a.id')
                               ->where  ('a.responsable = ?1')
                               ->orderBy('a.titre', 'ASC')
                               ->setParameter(1,$array_options['user_id']);
                break;
            }

            case 'ROLE_MEMBRE':
            {
                break;
            }

            case 'ROLE_VISITEUR':
            {
                break;
            }

            default :
            {
                $result =  $this->createQueryBuilder('a','a.id')
                                ->orderBy('a.titre', 'ASC');
                break;
            }
        }

        return $result;
    }

    public function findAllTermines()
    {
        return $this->createQueryBuilder('a','a.id')
                ->where('a.definestime < :datef')
                ->setParameter('datef', new \DateTime('now') )
                ->orderBy('a.titre', 'ASC')
                ->getQuery()
                ->getResult();
    }

    /**
     * @param null $array_options
     * @return array
     */

    public function findAllProjets($array_options = null)
    {
        return $this->findAllProjetsBuilder($array_options)->getQuery()->getResult();
    }

    public function findInternationaux()
    {
        return $this->createQueryBuilder('p')
                ->where('p.projetInternational = 1')
                ->andWhere('p.actif = 1')
                ->orderBy('p.titre', 'ASC')
                ->getQuery()
            ->getResult();
    }

    public function findAllProjetsResponsableBuilder($user)
    {
        return $this->createQueryBuilder('e')
            ->where('e.responsable = :user')
            ->setParameter('user', $user->getId())
            ->orderBy('e.actif, e.titre', 'ASC');
    }

    public function findAllProjetsResponsable($user)
    {
        return $this->createQueryBuilder('e')
            ->where('e.responsable = :user')
            ->setParameter('user', $user)
            ->orderBy('e.actif, e.titre', 'ASC')
            ->getQuery()
            ->getResult();
    }

    public function findAll()
    {
        return $this->findBy([], ['titre' => 'ASC']);
    }
}
