<?php

namespace App\Repository;

use App\Entity\Projets;
use App\Entity\ProjetsHasEquipes;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * ProjetsHasEquipesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProjetsHasEquipesRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, ProjetsHasEquipes::class);
    }

    public function findAllProjetsFromEquipeBuilder($id_projet)
    {
        return $this->createQueryBuilder('a','a.id')
            ->select ('a')
            ->where('a.projet = ?1')
            ->innerJoin('a.equipe', 'b')
            ->setParameter(1,$id_projet);
    }

    public function findAllProjetsFromEquipe ($id_projet)
    {
        return $this->findAllProjetsFromEquipeBuilder($id_projet)->getQuery()->getResult();
    }

    public function getArrayIdFromProjetsEquipes ($id_projet)
    {
        $result = [];
        $array  =  $this->findAllProjetsFromEquipe($id_projet);

        foreach ($array as $key=>$value)
        {
            $id = $value->getEquipe()->getId();

            $result[] = $id;
        }
        return $result;
    }

    public function findByEquipe(int $equipe)
    {
        return $this->createQueryBuilder('e')
            ->innerJoin(Projets::class, 'p', 'WITH', 'p.id = e.projet')
            ->where('e.equipe = :id')
            ->setParameter('id', $equipe)
            ->orderBy('p.titre', 'ASC')
            ->getQuery()
            ->getResult();
    }
}
