<?php

namespace App\Repository;

use App\Entity\Slider;
use Doctrine\Bundle\DoctrineBundle\Repository\ServiceEntityRepository;
use Doctrine\Persistence\ManagerRegistry;

/**
 * SliderRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SliderRepository  extends ServiceEntityRepository
{
    public function __construct(ManagerRegistry $registry)
    {
        parent::__construct($registry, Slider::class);
    }

    /**
     * @param null $array_options
     */
    public function findAllSliderBuilder($array_options = null): ?\Doctrine\ORM\QueryBuilder
    {
        $result = null;

        switch ($array_options['role'])
        {
            case 'ROLE_ADMINISTRATEUR':
            {
                $result = $this->createQueryBuilder('a','a.id')
                               ->orderBy('a.url', 'ASC');
                break;
            }

            case 'ROLE_RESPONSABLE':
            {

                break;
            }

            case 'ROLE_MEMBRE':
            {
                break;
            }

            case 'ROLE_VISITEUR':
            {
                break;
            }

            default :
            {
                $result = $this->createQueryBuilder('a','a.id')
                               ->orderBy('a.url', 'ASC');
                break;
            }
        }

        return $result;
    }


    /**
     * @param null $array_options
     * @return array
     */

    public function findAllSlider($array_options = null)
    {
        return $this->findAllSliderBuilder($array_options)->getQuery()->getResult();
    }
}
